Add switch_mfa_session command

diff --git a/bin/sts_session_manager b/bin/sts_session_manager
--- a/bin/sts_session_manager
+++ b/bin/sts_session_manager
@@ -12,9 +12,23 @@ function __validate() {
         exit 1
     fi
 
-    if ! aws configure get role_arn > /dev/null; then
-        echo "Error: role_arn is not set for this AWS_PROFILE" >&2
-        exit 1
+    if [ "${SUBCOMMAND}" == "switch_mfa_session" ]; then
+        if [ -z "${MFA_TOKEN}" ]; then
+            echo "Error: The second argument is required for the subcommand switch_mfa_token" >&2
+            exit 1
+        fi
+
+        if ! $(echo "${MFA_TOKEN}" | grep -q -E "\d{6}"); then
+            echo "Error: mfa_token must be a 6 digit number" >&2
+            exit 1
+        fi
+    fi
+
+    if [ "${SUBCOMMAND}" == "switch_role" ]; then
+        if ! aws configure get role_arn > /dev/null; then
+            echo "Error: role_arn is not set for this AWS_PROFILE" >&2
+            exit 1
+        fi
     fi
 }
 
@@ -46,7 +60,7 @@ function switch_role() {
     __validate
 
     local CACHE_FILE
-    CACHE_FILE="${CACHE_DIR}/$(echo -n "${AWS_PROFILE}" | openssl sha1 | sed "s/^SHA1(stdin)=\ //").json"
+    CACHE_FILE="${CACHE_DIR}/switch_role-$(echo -n "${AWS_PROFILE}" | openssl sha1 | sed "s/^SHA1(stdin)=\ //").json"
 
     local SESSION_NAME
     SESSION_NAME="${SESSION_NAME:=$(whoami)}"
@@ -81,6 +95,55 @@ function switch_role() {
         echo "AWS STS session token is expired." >&2
         echo "Recreate AWS STS session token..." >&2
         ${STS_ASSUME_ROLE_COMMAND} > "${CACHE_FILE}"
+    fi
+
+    cat <<- EOL
+		export AWS_ACCESS_KEY_ID=$(jq -r ".Credentials.AccessKeyId" < "${CACHE_FILE}")
+		export AWS_SECRET_ACCESS_KEY=$(jq -r ".Credentials.SecretAccessKey" < "${CACHE_FILE}")
+		export AWS_SESSION_TOKEN=$(jq -r ".Credentials.SessionToken" < "${CACHE_FILE}")
+		export AWS_SESSION_EXPIRATION="$("${DATE_CMD}" -d "${EXPIRATION}" --iso-8601=seconds)"
+	EOL
+}
+
+function switch_mfa_session() {
+    __validate
+
+    local CACHE_FILE
+    CACHE_FILE="${CACHE_DIR}/switch_mfa_session-$(echo -n "${AWS_PROFILE}" | openssl sha1 | sed "s/^SHA1(stdin)=\ //").json"
+
+    local SESSION_NAME
+    SESSION_NAME="${SESSION_NAME:=$(whoami)}"
+
+    local DURATION_SECONDS
+    DURATION_SECONDS="${DURATION_SECONDS:=$((60 * 60))}"
+
+    local STS_GET_SESSION_TOKEN_COMMAND
+    STS_GET_SESSION_TOKEN_COMMAND="aws sts get-session-token --serial-number $(aws configure get mfa_serial) --token-code ${MFA_TOKEN} --duration-seconds ${DURATION_SECONDS}"
+
+    if [ ! -s "${CACHE_FILE}" ]; then
+        echo "Create new AWS STS session token..." >&2
+        ${STS_GET_SESSION_TOKEN_COMMAND} > "${CACHE_FILE}"
+    fi
+
+    if [ "$(uname)" == "Darwin" ]; then
+        local DATE_CMD="gdate"
+    else
+        local DATE_CMD="date"
+    fi
+
+    local EXPIRATION
+    EXPIRATION=$(jq -r ".Credentials.Expiration" < "${CACHE_FILE}")
+
+    local EXPIRATION_UNIXTIME
+    EXPIRATION_UNIXTIME=$("${DATE_CMD}" -d "${EXPIRATION}" "+%s")
+
+    local NOW_UNIXTIME
+    NOW_UNIXTIME=$("${DATE_CMD}" "+%s")
+
+    if [ "${EXPIRATION_UNIXTIME}" -lt "${NOW_UNIXTIME}" ]; then
+        echo "AWS STS session token is expired." >&2
+        echo "Recreate AWS STS session token..." >&2
+        ${STS_GET_SESSION_TOKEN_COMMAND} > "${CACHE_FILE}"
     fi
 
     cat <<- EOL
@@ -127,18 +190,22 @@ function usage() {
     cat <<- EOL
 		Usage: ${COMMAND} <subcommand>
 		Subcommands:
-		    ${COMMAND} check_required_tools | check -- Check required tools
-		    ${COMMAND} switch_role                  -- Print switch_role export command
-		    ${COMMAND} switch_back                  -- Print switch_back unset command
-		    ${COMMAND} list | ls                    -- List sts cache file
-		    ${COMMAND} show                         -- Show sts cache file detail
-		    ${COMMAND} remove | rm                  -- Remove sts cache file
+		    ${COMMAND} check_required_tools | check   -- Check required tools
+		    ${COMMAND} switch_role                    -- Print switch_role export command
+            ${COMMAND} switch_mfa_session <mfa_token> -- Print switch_mfa_session export command
+		    ${COMMAND} switch_back                    -- Print switch_back unset command
+		    ${COMMAND} list | ls                      -- List sts cache file
+		    ${COMMAND} show                           -- Show sts cache file detail
+		    ${COMMAND} remove | rm                    -- Remove sts cache file
 	EOL
     exit 1
 }
 
 SUBCOMMAND="${1:-""}"
 readonly SUBCOMMAND
+
+MFA_TOKEN="${2:-""}"
+readonly MFA_TOKEN
 
 CACHE_DIR="${HOME}/.aws/cli/cache"
 readonly CACHE_DIR
@@ -149,6 +216,9 @@ case "${SUBCOMMAND}" in
         ;;
     switch_role)
         switch_role
+        ;;
+    switch_mfa_session)
+        switch_mfa_session
         ;;
     switch_back)
         switch_back
